// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyaQaAgPcirnANR72OQ1JklDZxn45TXb4',
    appId: '1:409689146827:web:80cd99ee7c21e1f146224e',
    messagingSenderId: '409689146827',
    projectId: 'chat-app-3f8ca',
    authDomain: 'chat-app-3f8ca.firebaseapp.com',
    storageBucket: 'chat-app-3f8ca.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6E9MxxWzuN_k6VRI8L5LYliaYJEJ846g',
    appId: '1:409689146827:android:1a9cf8f23b1b300646224e',
    messagingSenderId: '409689146827',
    projectId: 'chat-app-3f8ca',
    storageBucket: 'chat-app-3f8ca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-PBjKQxM9gbt40yRMhCwEfN9j7rOr7V0',
    appId: '1:409689146827:ios:e378f3db82c0451346224e',
    messagingSenderId: '409689146827',
    projectId: 'chat-app-3f8ca',
    storageBucket: 'chat-app-3f8ca.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-PBjKQxM9gbt40yRMhCwEfN9j7rOr7V0',
    appId: '1:409689146827:ios:e378f3db82c0451346224e',
    messagingSenderId: '409689146827',
    projectId: 'chat-app-3f8ca',
    storageBucket: 'chat-app-3f8ca.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyaQaAgPcirnANR72OQ1JklDZxn45TXb4',
    appId: '1:409689146827:web:0473b85d26e079f646224e',
    messagingSenderId: '409689146827',
    projectId: 'chat-app-3f8ca',
    authDomain: 'chat-app-3f8ca.firebaseapp.com',
    storageBucket: 'chat-app-3f8ca.appspot.com',
  );
}
